version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: muscle_analytics
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d muscle_analytics"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://dev:devpass@postgres:5432/muscle_analytics
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests

volumes:
  postgres_data: